### ISSUE TITLE
Lessons containing "" in their titles are generating an error, script stops downloading 

### ISSUE THREAD

**Issue by belhajManel** [umarfarouk98/KKL#2]
For example : in the CKA CERTIFICATION COURSE – CERTIFIED KUBERNETES Administrator we have a lesson named [Install “Kubernetes the kubeadm way”] Link :(https://kodekloud.com/lessons/install-kubernetes-the-kubeadm-way/), the script in this case saves a folder named as install and ignores all the rest of the string resulting in a path error in the script and thus the program stops running. This problem also show in the ckad course. Any sloution for this?

**Comment by fyunusa** [comment]
Thanks for raising up this issue, i'll look into it and get back to you soon.

**Comment by fyunusa** [comment]
> For example : in the CKA CERTIFICATION COURSE – CERTIFIED KUBERNETES Administrator we have a lesson named [Install “Kubernetes the kubeadm way”] Link :(https://kodekloud.com/lessons/install-kubernetes-the-kubeadm-way/), the script in this case saves a folder named as install and ignores all the rest of the string resulting in a path error in the script and thus the program stops running. This problem also show in the ckad course. Any sloution for this?

Try to run your downloader again and send me a feedback

**Comment by pemiolatunji** [comment]
> For example : in the CKA CERTIFICATION COURSE – CERTIFIED KUBERNETES Administrator we have a lesson named [Install “Kubernetes the kubeadm way”] Link :(https://kodekloud.com/lessons/install-kubernetes-the-kubeadm-way/), the script in this case saves a folder named as install and ignores all the rest of the string resulting in a path error in the script and thus the program stops running. This problem also show in the ckad course. Any sloution for this?

I had similar issue with shell script course. I'm currently checking with the update if it works.

**Comment by fyunusa** [comment]
Have you confirmed from your end too, as i'll mark the issue as closed

**Comment by belhajManel** [comment]
still not fixed for me. Here is the message error in the cmd : 
![image](https://user-images.githubusercontent.com/77749468/192119251-f6b94a24-fec0-4bf1-8101-fa002bdacfb8.png)

and this is the file structure :  
![image](https://user-images.githubusercontent.com/77749468/192119268-abde6eae-ae91-4055-b483-30ea2e6b38d2.png)

**Comment by fyunusa** [comment]
ok i'll check on it again

**Comment by fyunusa** [comment]
> https://kodekloud.com/lessons/install-kubernetes-the-kubeadm-way/

Did you pulled from the recent update i pushed?

**Comment by belhajManel** [comment]
@umarfarouk98 yes I did, I'm also investigating this problem, I'll keep you updated. Great work by the way.

**Comment by fyunusa** [comment]
> @umarfarouk98 yes I did, I'm also investigating this problem, I'll keep you updated. Great work by the way.

Thanks, you can also refer your friends to make use of it and also don't forget to give a star

**Comment by fyunusa** [comment]
> @umarfarouk98 yes I did, I'm also investigating this problem, I'll keep you updated. Great work by the way.

I just pushed a recent update now to cater for when there's no response from the site which might be caused due to network issues.
You might want to try this to solve the error you getting
